### ISSUE TITLE
peerplays dont compile in ubuntu 18.04

### ISSUE THREAD

**Issue by oxarbitrage** [PBSA/peerplays#24]
i think it is by the openssl 1.1. tried with different boost versions and it is the same thing. bitshares haves a patch for this, peerplays will need to port.

log:

```
[  8%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/thread/thread.cpp.o
In file included from /usr/include/boost/coroutine/stack_context.hpp:14:0,
                 from /home/alfredo/CLionProjects/peerplays/libraries/fc/src/thread/context.hpp:10,
                 from /home/alfredo/CLionProjects/peerplays/libraries/fc/src/thread/thread_d.hpp:5,
                 from /home/alfredo/CLionProjects/peerplays/libraries/fc/src/thread/thread.cpp:5:
/usr/include/boost/coroutine/detail/config.hpp:17:4: warning: #warning "Boost.Coroutine is now deprecated. Please switch to Boost.Coroutine2. To disable this warning message, define BOOST_COROUTINES_NO_DEPRECATION_WARNING." [-Wcpp]
 #  warning                  "Boost.Coroutine is now deprecated. Please switch to Boost.Coroutine2. To disable this warning message, define BOOST_COROUTINES_NO_DEPRECATION_WARNING."
    ^~~~~~~
In file included from /home/alfredo/CLionProjects/peerplays/libraries/fc/src/thread/thread_d.hpp:5:0,
                 from /home/alfredo/CLionProjects/peerplays/libraries/fc/src/thread/thread.cpp:5:
/home/alfredo/CLionProjects/peerplays/libraries/fc/src/thread/context.hpp:215:9: error: ‘fcontext_t’ in namespace ‘bc’ does not name a type
     bc::fcontext_t               my_context;
         ^~~~~~~~~~
/home/alfredo/CLionProjects/peerplays/libraries/fc/src/thread/context.hpp: In constructor ‘fc::context::context(void (*)(intptr_t), stack_allocator&, fc::thread*)’:
/home/alfredo/CLionProjects/peerplays/libraries/fc/src/thread/context.hpp:69:6: error: ‘my_context’ was not declared in this scope
      my_context = bc::make_fcontext( stack_ctx.sp, stack_ctx.size, sf);
      ^~~~~~~~~~
/home/alfredo/CLionProjects/peerplays/libraries/fc/src/thread/context.hpp:69:6: note: suggested alternative: ‘context’
      my_context = bc::make_fcontext( stack_ctx.sp, stack_ctx.size, sf);
      ^~~~~~~~~~
      context
/home/alfredo/CLionProjects/peerplays/libraries/fc/src/thread/context.hpp:69:23: error: ‘make_fcontext’ is not a member of ‘bc’
      my_context = bc::make_fcontext( stack_ctx.sp, stack_ctx.size, sf);
                       ^~~~~~~~~~~~~
/home/alfredo/CLionProjects/peerplays/libraries/fc/src/thread/context.hpp:69:23: note: suggested alternative: ‘stack_context’
      my_context = bc::make_fcontext( stack_ctx.sp, stack_ctx.size, sf);
                       ^~~~~~~~~~~~~
                       stack_context
/home/alfredo/CLionProjects/peerplays/libraries/fc/src/thread/context.hpp: In constructor ‘fc::context::context(fc::thread*)’:
/home/alfredo/CLionProjects/peerplays/libraries/fc/src/thread/context.hpp:88:6: error: class ‘fc::context’ does not have any field named ‘my_context’
      my_context(nullptr),
      ^~~~~~~~~~
In file included from /home/alfredo/CLionProjects/peerplays/libraries/fc/src/thread/thread.cpp:5:0:
/home/alfredo/CLionProjects/peerplays/libraries/fc/src/thread/thread_d.hpp: In member function ‘bool fc::thread_d::start_next_fiber(bool)’:
/home/alfredo/CLionProjects/peerplays/libraries/fc/src/thread/thread_d.hpp:401:21: error: ‘jump_fcontext’ is not a member of ‘bc’
                 bc::jump_fcontext( &prev->my_context, next->my_context, 0 );
                     ^~~~~~~~~~~~~
/home/alfredo/CLionProjects/peerplays/libraries/fc/src/thread/thread_d.hpp:401:21: note: suggested alternative: ‘stack_context’
                 bc::jump_fcontext( &prev->my_context, next->my_context, 0 );
                     ^~~~~~~~~~~~~
                     stack_context
/home/alfredo/CLionProjects/peerplays/libraries/fc/src/thread/thread_d.hpp:401:43: error: ‘struct fc::context’ has no member named ‘my_context’; did you mean ‘context’?
                 bc::jump_fcontext( &prev->my_context, next->my_context, 0 );
                                           ^~~~~~~~~~
                                           context
/home/alfredo/CLionProjects/peerplays/libraries/fc/src/thread/thread_d.hpp:401:61: error: ‘struct fc::context’ has no member named ‘my_context’; did you mean ‘context’?
                 bc::jump_fcontext( &prev->my_context, next->my_context, 0 );
                                                             ^~~~~~~~~~
                                                             context
/home/alfredo/CLionProjects/peerplays/libraries/fc/src/thread/thread_d.hpp:443:21: error: ‘jump_fcontext’ is not a member of ‘bc’
                 bc::jump_fcontext( &prev->my_context, next->my_context, (intptr_t)this );
                     ^~~~~~~~~~~~~
/home/alfredo/CLionProjects/peerplays/libraries/fc/src/thread/thread_d.hpp:443:21: note: suggested alternative: ‘stack_context’
                 bc::jump_fcontext( &prev->my_context, next->my_context, (intptr_t)this );
                     ^~~~~~~~~~~~~
                     stack_context
/home/alfredo/CLionProjects/peerplays/libraries/fc/src/thread/thread_d.hpp:443:43: error: ‘struct fc::context’ has no member named ‘my_context’; did you mean ‘context’?
                 bc::jump_fcontext( &prev->my_context, next->my_context, (intptr_t)this );
                                           ^~~~~~~~~~
                                           context
/home/alfredo/CLionProjects/peerplays/libraries/fc/src/thread/thread_d.hpp:443:61: error: ‘struct fc::context’ has no member named ‘my_context’; did you mean ‘context’?
                 bc::jump_fcontext( &prev->my_context, next->my_context, (intptr_t)this );
                                                             ^~~~~~~~~~
                                                             context
libraries/fc/CMakeFiles/fc.dir/build.make:182: recipe for target 'libraries/fc/CMakeFiles/fc.dir/src/thread/thread.cpp.o' failed
make[2]: *** [libraries/fc/CMakeFiles/fc.dir/src/thread/thread.cpp.o] Error 1
CMakeFiles/Makefile2:397: recipe for target 'libraries/fc/CMakeFiles/fc.dir/all' failed
make[1]: *** [libraries/fc/CMakeFiles/fc.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by oxarbitrage** [comment]
related pull requests to allow openssl 1.1 in bitshares:
https://github.com/bitshares/bitshares-fc/pull/7
https://github.com/bitshares/bitshares-core/pull/921

**Comment by bobinson** [comment]
fixed in https://github.com/peerplays-network/peerplays/
